blank_issues_enabled: false

contact_links:

  - name: Ask an question / advise on using tldfinder
    url: https://github.com/projectdiscovery/tldfinder/discussions/categories/q-a
    about: Ask a question or request support for using tldfinder

  - name: Share idea / feature to discuss for tldfinder
    url: https://github.com/projectdiscovery/tldfinder/discussions/categories/ideas
    about: Share idea / feature to discuss for tldfinder

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication