name: 🔨 Release Test

on:
  pull_request:
    paths:
      - '**.go'
      - '**.mod'
  workflow_dispatch:

jobs:
  release-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out code"
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Set up Go
        uses: projectdiscovery/actions/setup/go@v1
      
      - name: Release snapshot
        uses: projectdiscovery/actions/goreleaser@v1
